# Generated by Django 4.1.3 on 2022-11-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'doctor'), ('2', 'patient'), ('3', 'super_user')], max_length=1, null=True),
        ),
    ]
